[tool.poetry]
name = "course-flask"
version = "0.1.0"
description = ""
authors = ["marcustas <stas.chernov@casafari.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.0"
pydantic = "^2.4.2"
flask-sqlalchemy = "^3.1.1"
flask-migrate = "^4.0.5"
pydantic-settings = "^2.0.3"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
