"""empty message

Revision ID: 41d2772a113d
Revises: e08fc0218f8b
Create Date: 2025-06-09 00:45:28.796915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d2772a113d'
down_revision = 'e08fc0218f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
